CREATE TABLE Platform (
	platformID CHAR(8) NOT NULL PRIMARY KEY,
	platformName VARCHAR(50)
);

CREATE TABLE Player (
	playerID CHAR(8) NOT NULL PRIMARY KEY,
	playerName VARCHAR(50)
);

CREATE TABLE Game (
	gameID CHAR(8) NOT NULL PRIMARY KEY,
	gameName VARCHAR(50)
);

CREATE TABLE IsPlatformOf (
	FK_platformID CHAR(8) NOT NULL,
	FK_gameID CHAR(8) NOT NULL,
	FOREIGN KEY (FK_platformID) REFERENCES Platform (platformID) ON DELETE CASCADE,
	FOREIGN KEY (FK_gameID) REFERENCES Game (gameID) ON DELETE CASCADE
);

CREATE TABLE Category (
	categoryID CHAR(8) NOT NULL PRIMARY KEY,
	categoryName VARCHAR(50),
	FK_gameID CHAR(8) NOT NULL,
	FOREIGN KEY (FK_gameID) REFERENCES Game (gameID) ON DELETE CASCADE
);

CREATE TABLE Moderator (
	role VARCHAR(20),
	FK_gameID CHAR(8) NOT NULL,
	FK_playerID CHAR(8) NOT NULL,
	FOREIGN KEY (FK_gameID) REFERENCES Game (gameID) ON DELETE CASCADE,
	FOREIGN KEY (FK_playerID) REFERENCES Player (playerID) ON DELETE CASCADE
);

CREATE TABLE Run (
	runID CHAR(8) NOT NULL PRIMARY KEY,
	runTime REAL NOT NULL,
	runDate CHAR(10),
	FK_categoryID CHAR(8) NOT NULL,
	FOREIGN KEY (FK_categoryID) REFERENCES Category (categoryID) ON DELETE CASCADE
);

CREATE TABLE Perform (
	FK_runID CHAR(8) NOT NULL,
	FK_playerID CHAR(8) NOT NULL,
	FOREIGN KEY (FK_runID) REFERENCES Run (runID) ON DELETE CASCADE,
	FOREIGN KEY (FK_playerID) REFERENCES Player (playerID) ON DELETE CASCADE
);

CREATE INDEX PlayerIndex ON Player(playerID);
CREATE INDEX GameIndex ON Game(gameID);
CREATE INDEX CategoryIndex ON Category(categoryID);
CREATE INDEX RunIndex ON Run(runID);
CREATE INDEX PlatformIndex ON Platform(platformID);
CREATE INDEX PerformIndex ON Perform(FK_runID,FK_playerID);
CREATE INDEX IsPlatformIndex ON IsPlatformOf(FK_platformID,FK_gameID);