CREATE TABLE User (
	UserID INTEGER NOT NULL PRIMARY KEY,
	Username CHAR(50),
	Verified CHAR(10),
	Followers INTEGER
);

CREATE TABLE Tweet (
	TweetID INTEGER NOT NULL PRIMARY KEY,
	FK_UserID INTEGER NOT NULL,
	Content CHAR(200),
	FOREIGN KEY (FK_UserID) REFERENCES User (UserID)
);

CREATE TABLE Likes (
	LikeID INTEGER NOT NULL PRIMARY KEY,
	FK_UserID INTEGER NOT NULL,
	FK_TweetID INTEGER,
	FK_CommentID INTEGER,
	FOREIGN KEY (FK_UserID) REFERENCES User (UserID),
	FOREIGN KEY (FK_TweetID) REFERENCES Tweet (TweetID),
	FOREIGN KEY (FK_CommentID) REFERENCES Comment (CommentID)
);

CREATE TABLE Comments (
	CommentID INTEGER NOT NULL PRIMARY KEY,
	FK_UserID INTEGER NOT NULL,
	FK_TweetID INTEGER,
	FK_CommentID INTEGER,
	Content CHAR(200),
	FOREIGN KEY (FK_UserID) REFERENCES User (UserID),
	FOREIGN KEY (FK_TweetID) REFERENCES Tweet (TweetID),
	FOREIGN KEY (FK_CommentID) REFERENCES Comments (CommentID)
);

CREATE TABLE Hashtag (
	HashtagID INTEGER PRIMARY KEY,
	Content CHAR(50)
);

CREATE TABLE HashtagsInContent (
	FK_HashtagID INTEGER NOT NULL,
	FK_TweetID INTEGER,
	FK_CommentID INTEGER,
	FOREIGN KEY (FK_HashtagID) REFERENCES Hashtag (HashtagID),
	FOREIGN KEY (FK_TweetID) REFERENCES Tweet (TweetID),
	FOREIGN KEY (FK_CommentID) REFERENCES Comments (CommentID)
);